services:
  postgres:
    image: postgres:18.0-alpine3.22
    container_name: reservations_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: reservations
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8.2.2-alpine
    container_name: reservations_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
